version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"
        format: "%(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.NullHandler
        level: DEBUG
        formatter: simple

root:
  level: INFO
  handlers: [console]

loggers:

    api_logic_server_cli.api_logic_server:
        # level: DEBUG
        handlers: [console]
        propagate: no

    create_from_model.api_logic_server_utils:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    sqlacodegen_wrapper.sqlacodegen.sqlacodegen.codegen:   
#        level: DEBUG
        handlers: [console]
        propagate: no

# find  a.  Create Models
    api_logic_server_cli.sqlacodegen_wrapper.sqlacodegen_wrapper:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    create_from_model.model_creation_services:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    api_logic_server_cli.create_from_model.ui_admin_creator:   
#         level: DEBUG
        handlers: [console]
        propagate: no
        
    ModelMigrator:   
        level: DEBUG
        handlers: [console]
        propagate: no

    ont-app:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    api_logic_server_cli.genai.genai:   
        level: DEBUG
        handlers: [console]
        propagate: no

    api_logic_server_cli.genai.genai_svcs:   
        level: INFO
        handlers: [console]
        propagate: no

    openai:   
        level: WARNING
        handlers: [console]
        propagate: no

    httpx:   
        level: WARNING
        handlers: [console]
        propagate: no

    api_logic_server_cli.genai.genai_admin_app:   
        level: INFO
        handlers: [console]
        propagate: no


    api_logic_server_cli.genai.genai_logic_builder:   
        level: DEBUG
        handlers: [console]
        propagate: no


    api_logic_server_cli.genai.genai_utils:   
        level: DEBUG
        handlers: [console]
        propagate: no
