# Run WebGenAI locally from docker container

# Before running, update ./system/genai/webg_local/webg_config/web_genai.txt
# See: https://apilogicserver.github.io/Docs/WebGenAI-CLI/#configuration

# cd <manager>  

# docker compose -f webgenai/docker-compose-webg.yml up
# docker compose -f webgenai/docker-compose-webg.yml down

# to start in interactive mode:
# docker compose -f webgenai/docker-compose-webg.yml run web_genai

name: webgenie
services:
    web_genai:
        stdin_open: true
        tty: true
        container_name: webgenai
        ports:
            - 8282:80
        env_file:
            - ./webg_config/web_genai.txt
        volumes:
            - ./webg_temp:/tmp
            - ./webg_config:/config
            - ./webg_projects:/opt/projects
        image: apilogicserver/web_genai 
        user: root
        environment:
            - GENAI_LOGIC_APIKEY=<paste license here from registration email>
            - APILOGICSERVER_CHATGPT_APIKEY=<sk-proj-your-openai-key-here>    