# Run WebGenAI locally from docker container

# Before running, update ./system/genai/webg_local/webg_config/web_genai.txt
# See: https://apilogicserver.github.io/Docs/WebGenAI-CLI/#configuration

# cd <manager>  

# docker compose -f webgenai/docker-compose-nw.yml up
# docker compose -f webgenai/docker-compose-nw.yml down

# if you have run docker compose up (above), you must run docker compose down to run directly:

# docker run -it --rm --name webgenai -p 8282:80  --env-file ./webgenai/webg_config/web_genai.txt -v ./webgenai/webg_temp:/tmp  -v ./webgenai/webg_config:/config -v ./webgenai/webg_projects:/opt/projects -v ./samples/nw_sample:/app apilogicserver/web_genai

# FIXME - docker standard images runs with
# docker run -it --rm --name api_logic_project -p 5656:5656  --env-file ./devops/docker-standard-image/env.list -v ./:/app apilogicserver/api_logic_server python3 /app/api_logic_server_run.py

name: webgenai
services:
    web_genai:
        stdin_open: true
        tty: true
        container_name: webgenai
        ports:
            - 8282:80
        env_file:
            - ./webg_config/web_genai.txt
        volumes:
            - ./webg_temp:/tmp
            - ./webg_config:/config
            - ./webg_projects:/opt/projects
            - ./samples/nw_sample:/app
        image: apilogicserver/web_genai 
        user: root
        command: ["/bin/bash"]
        # command: ["python /app/api_logic_server_run.py"]