create database herboDeSonia;

use herboDeSonia;

CREATE TABLE `Cliente` (
  `Tipo` text DEFAULT NULL,
  `FechaAlta` date DEFAULT NULL,
  `TipoCliente` text DEFAULT NULL,
  `DNI_CIF` text DEFAULT NULL,
  `BIC` text DEFAULT NULL,
  `IBAN` text DEFAULT NULL,
  `NCuenta` int(11) NOT NULL AUTO_INCREMENT,
  `NombreCorto` text DEFAULT NULL,
  `NombreCompleto` text DEFAULT NULL,
  `Calle` text DEFAULT NULL,
  `ExtCalle` text DEFAULT NULL,
  `Localidad` text DEFAULT NULL,
  `Provincia` text DEFAULT NULL,
  `CodPostal` text DEFAULT NULL,
  `Tlf` text DEFAULT NULL,
  `Email` text DEFAULT NULL,
  `Web` text DEFAULT NULL,
  `FPago` text DEFAULT NULL,
  `CC` text DEFAULT NULL,
  `DtoGl` text DEFAULT NULL,
  `NCopFact` text DEFAULT NULL,
  `Contacto` text DEFAULT NULL,
  `Recomendado` text DEFAULT NULL,
  `Comentarios` text DEFAULT NULL,
  `Notific` text DEFAULT NULL,
  `DeBaja` text DEFAULT NULL,
  `FechaBaja` date DEFAULT NULL,
  `CreadorPor` text DEFAULT NULL,
  `SumaVentas` decimal(11,2) DEFAULT NULL,
  `PuntosGenerados` int(11) DEFAULT NULL,
  `PuntosUsados` int(11) DEFAULT NULL,
  `SaldoParaPuntos` decimal(11,2) DEFAULT NULL,
  PRIMARY KEY (`NCuenta`)
) ENGINE=InnoDB AUTO_INCREMENT=18890 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Compras_CAB` (
  `SerieNúmero` varchar(11) DEFAULT NULL,
  `Fecha` datetime DEFAULT NULL,
  `RazónSocial` text DEFAULT NULL,
  `BaseImponible` decimal(11,2) DEFAULT NULL,
  `ImporteIVA` decimal(11,2) DEFAULT NULL,
  `ImporteRecargoEq` decimal(11,2) DEFAULT NULL,
  `TotalAlbCompra` decimal(11,2) DEFAULT NULL,
  `idCabCompras` int(11) NOT NULL AUTO_INCREMENT,
  `ImporteIVAReducido` decimal(11,2) DEFAULT NULL,
  `ImporteIVASuperReducido` decimal(11,2) DEFAULT NULL,
  `ImporteIVAAceitesPastas` decimal(11,2) DEFAULT NULL,
  `BaseIVAReducido` decimal(11,2) DEFAULT NULL,
  `BaseIVASuperReducido` decimal(11,2) DEFAULT NULL,
  `BaseIVAAceitesPastas` decimal(11,2) DEFAULT NULL,
  `BaseIVACero` decimal(11,2) DEFAULT NULL,
  `ImporteIVAGeneral` decimal(11,2) DEFAULT NULL,
  `BaseIVAGeneral` decimal(11,2) DEFAULT NULL,
  `TotalAlbCalculado` decimal(11,2) DEFAULT NULL,
  `tpcDtoProntoPago` decimal(5,2) DEFAULT NULL,
  `tpcDtoGlobal` decimal(5,2) DEFAULT NULL,
  `Tienda` text DEFAULT NULL,
  `NºCuentaProveedor` int(11) DEFAULT NULL,
  `idTienda` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`idCabCompras`),
  UNIQUE KEY `idCabCompras` (`SerieNúmero`) USING BTREE,
  KEY `IndexFecha` (`Fecha`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2856 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Compras_LIN` (
  `Tienda` text DEFAULT NULL,
  `NúmeroAlbarán` int(11) DEFAULT NULL,
  `AlbaránCompra` varchar(11) DEFAULT NULL,
  `NombreProveedor` text DEFAULT NULL,
  `FechaAlbarán` datetime DEFAULT NULL,
  `ImporteAlbarán` decimal(11,2) DEFAULT NULL,
  `ReferenciaProducto` int(11) DEFAULT NULL,
  `OLDReferenciaProducto` text DEFAULT NULL,
  `DescripciondelProducto` text DEFAULT NULL,
  `CódigodeBarras` bigint(20) DEFAULT NULL,
  `Cantidad` int(11) DEFAULT NULL,
  `PVPProducto` decimal(11,2) DEFAULT NULL,
  `PrecioLínea` decimal(11,2) DEFAULT NULL,
  `tpcIVA` decimal(11,2) DEFAULT NULL,
  `tpcDescuento1` decimal(5,2) DEFAULT NULL,
  `tpcDescuento2` decimal(5,2) DEFAULT NULL,
  `tpcDescuento3` decimal(5,2) DEFAULT NULL,
  `tpcDescuento4` decimal(5,2) DEFAULT NULL,
  `tpcDtoGlobal` decimal(5,2) DEFAULT NULL,
  `tpcDtoProntoPago` decimal(5,2) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Importe` decimal(11,2) DEFAULT NULL,
  `NºCuentaProveedor` int(11) DEFAULT NULL,
  `CantidadConCoste` int(11) DEFAULT NULL,
  `CantidadGratis` int(11) DEFAULT NULL,
  `PrecioCoste` decimal(11,2) DEFAULT NULL,
  `Lote` varchar(20) DEFAULT NULL,
  `idTienda` smallint(6) DEFAULT NULL,
  `FechaInventario` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_AlbaránCompra` (`AlbaránCompra`),
  KEY `Fk_Producto` (`idTienda`,`ReferenciaProducto`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=19021 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Producto` (
  `Referencia` int(11) NOT NULL,
  `Descripcion` text DEFAULT NULL,
  `DescripcionBreve` text DEFAULT NULL,
  `CodBarras` text DEFAULT NULL,
  `CodGenerico` text DEFAULT NULL,
  `FechaCreacion` text DEFAULT NULL,
  `PVP` float DEFAULT NULL,
  `PrecioCoste` float DEFAULT NULL,
  `Familia` text DEFAULT NULL,
  `SubFam` text DEFAULT NULL,
  `Stock` float DEFAULT NULL,
  `Ubicacion` text DEFAULT NULL,
  `IVA` text DEFAULT NULL,
  `Marca` text DEFAULT NULL,
  `Proveedor` text DEFAULT NULL,
  `Descatalogado` text DEFAULT NULL,
  `PublicarWeb` text DEFAULT NULL,
  `OfertaWeb` text DEFAULT NULL,
  `NovedadWeb` text DEFAULT NULL,
  `tipoIVA` smallint(6) DEFAULT NULL,
  `FechaUltPVP` datetime DEFAULT NULL,
  PRIMARY KEY (`Referencia`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Proveedor` (
  `DNICIF` text DEFAULT NULL,
  `RSocial` text DEFAULT NULL,
  `TipoProv` text DEFAULT NULL,
  `FPago` text DEFAULT NULL,
  `Facturación` text DEFAULT NULL,
  `Provincia` text DEFAULT NULL,
  `NºCuenta` int(11) NOT NULL AUTO_INCREMENT,
  `Calle` text DEFAULT NULL,
  `ExtCalle` text DEFAULT NULL,
  `Localidad` text DEFAULT NULL,
  `CPost` int(11) DEFAULT NULL,
  `E-mail` text DEFAULT NULL,
  `Web` text DEFAULT NULL,
  `BIC` text DEFAULT NULL,
  `IBAN` text DEFAULT NULL,
  `CC` text DEFAULT NULL,
  `Tlf1` text DEFAULT NULL,
  `Tlf2` text DEFAULT NULL,
  `Móvil` int(11) DEFAULT NULL,
  `Fax` text DEFAULT NULL,
  `Contacto` text DEFAULT NULL,
  `Comentarios` text DEFAULT NULL,
  `Notific` text DEFAULT NULL,
  `Debaja` text DEFAULT NULL,
  PRIMARY KEY (`NºCuenta`)
) ENGINE=InnoDB AUTO_INCREMENT=494 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



CREATE TABLE `StockTienda` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Tienda` char(20) NOT NULL,
  `Referencia` int(11) NOT NULL,
  `Marca` text DEFAULT NULL,
  `Producto` text DEFAULT NULL,
  `ÚltimaVenta` date DEFAULT NULL,
  `ÚltimaCompra` date DEFAULT NULL,
  `Unidades` float DEFAULT NULL,
  `PrecioCoste` float DEFAULT NULL,
  `PrecioCosteConIVA` float DEFAULT NULL,
  `PrecioCosteConIVA-Recargo` float DEFAULT NULL,
  `PCM` float DEFAULT NULL,
  `PCMconIVA` float DEFAULT NULL,
  `PCMconIVA-Recargo` float DEFAULT NULL,
  `PVP` float DEFAULT NULL,
  `PVPsinIVA` float DEFAULT NULL,
  `idTienda` smallint(6) NOT NULL,
  `StockInicial` int(11) DEFAULT NULL,
  `Entradas` int(11) DEFAULT NULL,
  `Salidas` int(11) DEFAULT NULL,
  `Stock` int(11) DEFAULT NULL,
  `FechaInventario` datetime DEFAULT NULL,
  PRIMARY KEY (`idTienda`,`Referencia`),
  UNIQUE KEY `ID` (`ID`),
  KEY `idx_Referencia` (`Referencia`)
) ENGINE=InnoDB AUTO_INCREMENT=229211 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Tienda` (
  `STOREDVALUE` int(11) NOT NULL AUTO_INCREMENT,
  `DISPLAYVALUE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`STOREDVALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Traspasos_LIN` (
  `Origen` text DEFAULT NULL,
  `Destino` text DEFAULT NULL,
  `Número` int(11) NOT NULL AUTO_INCREMENT,
  `Producto` text DEFAULT NULL,
  `Cantidad` int(11) DEFAULT NULL,
  `FechaTraspaso` datetime DEFAULT NULL,
  `PedidoProveedor` text DEFAULT NULL,
  `Referencia` int(11) DEFAULT NULL,
  PRIMARY KEY (`Número`),
  UNIQUE KEY `PK` (`Número`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=416347 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Ventas_CAB` (
  `Usuario` text DEFAULT NULL,
  `Tienda` text DEFAULT NULL,
  `Serie` text DEFAULT NULL,
  `Número` int(11) NOT NULL AUTO_INCREMENT,
  `VentaMostrador` text DEFAULT NULL,
  `FechaVenta` datetime DEFAULT NULL,
  `ImporteTotal` float DEFAULT NULL,
  `PrecioLínea` float DEFAULT NULL,
  `NombreOferta` text DEFAULT NULL,
  `tpcDtoGlobal` float DEFAULT NULL,
  `tpcDtoPP` float DEFAULT NULL,
  `ImporteBruto` float DEFAULT NULL,
  `FacturaSN` text DEFAULT NULL,
  `FechaFactura` text DEFAULT NULL,
  `NombreRazónSocialCliente` text DEFAULT NULL,
  `NombreComercialCliente` text DEFAULT NULL,
  `NCuentaCliente` int(11) DEFAULT NULL,
  `TipoCliente` text DEFAULT NULL,
  `NIFCliente` text DEFAULT NULL,
  `Teléfono` text DEFAULT NULL,
  `ImporteIVASuperReducido` float DEFAULT NULL,
  `ImporteIVAReducido` float DEFAULT NULL,
  `ImporteIVAAceitesPastas` float DEFAULT NULL,
  `ImporteIVAGeneral` float DEFAULT NULL,
  `BaseIVACero` float DEFAULT NULL,
  `BaseIVASuperReducido` float DEFAULT NULL,
  `BaseIVAReducido` float DEFAULT NULL,
  `BaseIVAAceitesPastas` float DEFAULT NULL,
  `BaseIVAGeneral` float DEFAULT NULL,
  `NumeroLineas` int(11) DEFAULT NULL,
  `TieneValesDto` bit(1) DEFAULT NULL,
  `Puntos` int(11) DEFAULT NULL,
  PRIMARY KEY (`Número`),
  KEY `FKCliente` (`NCuentaCliente`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=189335 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `Ventas_LIN` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Usuario` text DEFAULT NULL,
  `Tienda` text DEFAULT NULL,
  `Serie` text DEFAULT NULL,
  `Número` int(11) DEFAULT NULL,
  `VentaMostrador` text DEFAULT NULL,
  `FechaVenta` datetime DEFAULT NULL,
  `Producto` text DEFAULT NULL,
  `CódigoBarras` text DEFAULT NULL,
  `RefProducto` int(11) DEFAULT NULL,
  `OLDRefProducto` text DEFAULT NULL,
  `StockCantidad` float DEFAULT NULL,
  `FamiliaComercial` text DEFAULT NULL,
  `SubFamiliaComercial` text DEFAULT NULL,
  `Marca` text DEFAULT NULL,
  `CantidadVendida` float DEFAULT NULL,
  `LoteVendido` text DEFAULT NULL,
  `FechaCaducidad` text DEFAULT NULL,
  `ImporteTotal` float DEFAULT NULL,
  `PrecioLínea` float DEFAULT NULL,
  `tpcIVA` float DEFAULT NULL,
  `NombreOferta` text DEFAULT NULL,
  `tpcDtoLínea` float DEFAULT NULL,
  `tpcDtoGlobal` float DEFAULT NULL,
  `tpcDtoPP` float DEFAULT NULL,
  `ImporteBruto` float DEFAULT NULL,
  `FacturaSN` text DEFAULT NULL,
  `FechaFactura` text DEFAULT NULL,
  `NombreRazónSocialCliente` text DEFAULT NULL,
  `NombreComercialCliente` text DEFAULT NULL,
  `NCuentaCliente` int(11) DEFAULT NULL,
  `TipoCliente` text DEFAULT NULL,
  `NIFCliente` text DEFAULT NULL,
  `Teléfono` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKProducto` (`RefProducto`) USING BTREE,
  KEY `FKCliente` (`NCuentaCliente`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=122229 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

