#!/bin/bash

if [ $# -eq 0 ]
  then
    echo " "
    echo "  [Deletes and] Pulls [and rebuilds] react-admin ==> ApiLogicServer/api_logic_server_cli/safrs-react-admin-npm-build"
    echo " "
    echo "      sh install-react-admin [pull | go | clean ] [als-overlay]"
    echo " "
    echo "          pull    - pull git/safrs-react-admin                   (no als overlays)  <=="
    echo "          go      - use existing git/safrs-react-admin folder    (no als overlays)"
    echo "          clone   - delete and clone  git/safrs-react-admin      (no als overlays)"
    echo " "
    echo "          als-overlay   - delete / rebuild the safrs-react-admin folder, with als overlays"
    echo " "
    echo "      IMPORTANT - overwrites safrs-react-admin from react-admin/code - make sure that's up to date"
    echo " "
    exit 0
  fi

if [[ "$1" = "pull" ]]
  then
    # sudo chown $USER:$USER ../../safrs-react-admin
    echo ""
    cd ../../safrs-react-admin
    pwd  # at safrs-react-admin
    read -p "Press [Enter] to pull safrs-react-admin>"
    pwd
    git pull
    cd ../ApiLogicServer
fi

echo " "
if [[ "$1" = "clone" ]]
  then
    # sudo chown $USER:$USER ../../safrs-react-admin
    echo ""
    cd ../../
    pwd  # at dev
    read -p "Press [Enter] to delete / pull safrs-react-admin>"
    sudo rm -r safrs-react-admin
    pwd
    git clone https://github.com/thomaxxl/safrs-react-admin --depth=1
    cd ApiLogicServer
fi

if [[ "$1" = "go" ]]
  then
    echo "using existing safrs-react-admin"
    cd ..
fi

set +x
if [[ "$2" = "als-overlay" ]]
  then
    echo " "
    cd ../safrs-react-admin
    ls ../ApiLogicServer/react-admin/code
    read -p "Verify ls contains als code, and [Enter] to rebuild safrs-react-admin for API Logic Server>"
    set -x
    # cp ../ApiLogicServer/react-admin/code/Home-als.js src/components/Home.js
    cp ../ApiLogicServer/react-admin/code/Home-als.js src/components/ValH.js
    # cp ../ApiLogicServer/react-admin/code/Config-als.js src/Config.js
    npm install
    pwd
    ls
    read -p "npm install complete - check node_modules, and [Enter] rebuild react-admin for API Logic Server>"
    npm run build
    set +x
    cd ../ApiLogicServer
  fi

echo " "
pwd
echo " "
echo "copying build to als"
if [ -r tvf.txt ]
  then
    echo ".. correctly current in ApiLogicServer"
  else
    echo ".. Error - wrong directory"
    exit 1
fi
if [ -d ../safrs-react-admin/build ]
  then
    echo ".. safrs-react-admin/build exists"
    echo " "
  else
    echo ".. Error - safrs-react-admin/build NOT FOUND"
    exit 1
fi
echo "..rm -rf  api_logic_server_cli/create_from_model/safrs-react-admin-npm-build/*"
set +x
rm -rf api_logic_server_cli/create_from_model/safrs-react-admin-npm-build/*
set -x
cp -a ../safrs-react-admin/build/. api_logic_server_cli/create_from_model/safrs-react-admin-npm-build
echo " "
echo "you may wish to run:    git remote rm origin"
echo " "
exit 0

