version: '3'

# cd devops/keycloak
# docker compose --file docker-compose-nginx.yml up

services:
  app:
    image: apilogicserver/api_logic_server
    container_name: apilogicserver
    restart: always
    command: ApiLogicServer run --project_name=/servers/KeyCloakIntegration
    environment:
      - APILOGICPROJECT_VERBOSE=true
      - APILOGICPROJECT_CLIENT_URI=//${HOST_IP}
    ports:
      - 5656:5656
    volumes:
      # - $PWD/auth_provider.py:/home/api_logic_server/api_logic_server_cli/prototypes/base/security/authentication_provider/sql/auth_provider.py
      - $PWD/servers:/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/servers
      - $PWD/als:/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/api_logic_server_cli

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    restart: always
    #command: start --hostname-strict=false --proxy edge --hostname-url https://kc.hardened.be --hostname-strict-https=false
    command: start-dev --import-realm --proxy=edge --hostname-strict=false --hostname-strict-https=false
    ports:
        - 8080:8080
    volumes:
        - $PWD/import:/opt/keycloak/data/import
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=password

  nginx:
    image: nginx:latest
    depends_on: 
        - keycloak
    container_name: nginx
    volumes:
        - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
        - $PWD/nginx/cert.pem:/root/cert.pem
        - $PWD/nginx/key.pem:/root/key.pem
        - $PWD/nginx/admin-app:/usr/share/nginx/html/admin-app
    ports:
        - 80:80
        - 443:443
