#!/bin/bash

if [ $# -eq 0 ]
  then
    echo " "
    echo "Rebuilds react-admin into ApiLogicServer/api_logic_server_cli/safrs-react-admin-npm-build"
    echo " "
    echo " IMPORTANT - overwrites safrs-react-admin from react-admin/code - make sure that's up to date"
    echo " "
    echo "  sh rebuild-react-admin go"
    echo " "
    exit 0
  else
    echo " "
    read -p "Verify react-admin/code is current, correct yaml url, and [Enter] rebuild react-admin for API Logic Server"
    set -x
    pushd ../../safrs-react-admin
    git reset --hard origin/master
    ls ../ApiLogicServer/react-admin/code
    cp ../ApiLogicServer/react-admin/code/Home-als.js src/components/Home.js
    cp ../ApiLogicServer/react-admin/code/Config-als.js src/Config.js
    npm run build
    rm -rf ../ApiLogicServer/api_logic_server_cli/create_from_model/safrs-react-admin-npm-build/*
    cp -a ./build/. ../ApiLogicServer/api_logic_server_cli/create_from_model/safrs-react-admin-npm-build
    exit 0
fi
