#this is the api_test.feature
Feature: API GET Testing

  Scenario: GET STRESSTIMESTAMP Endpoint
    Given GET STRESSTIMESTAMP endpoint
    When GET STRESSTIMESTAMP API
    Then STRESSTIMESTAMP retrieved

  Scenario: GET STRESSCHARACTERVARYING Endpoint
    Given GET STRESSCHARACTERVARYING endpoint
    When GET STRESSCHARACTERVARYING API
    Then STRESSCHARACTERVARYING retrieved

  Scenario: GET STRESSTIMEWITHTIMEZONE Endpoint
    Given GET STRESSTIMEWITHTIMEZONE endpoint
    When GET STRESSTIMEWITHTIMEZONE API
    Then STRESSTIMEWITHTIMEZONE retrieved

  Scenario: GET STRESSREAL Endpoint
    Given GET STRESSREAL endpoint
    When GET STRESSREAL API
    Then STRESSREAL retrieved

  Scenario: GET STRESSBITARR Endpoint
    Given GET STRESSBITARR endpoint
    When GET STRESSBITARR API
    Then STRESSBITARR retrieved

  Scenario: GET STRESSBYTEAARR Endpoint
    Given GET STRESSBYTEAARR endpoint
    When GET STRESSBYTEAARR API
    Then STRESSBYTEAARR retrieved

  Scenario: GET STRESSTIMEARR Endpoint
    Given GET STRESSTIMEARR endpoint
    When GET STRESSTIMEARR API
    Then STRESSTIMEARR retrieved

  Scenario: GET STRESSCHARACTERVARYINGARR Endpoint
    Given GET STRESSCHARACTERVARYINGARR endpoint
    When GET STRESSCHARACTERVARYINGARR API
    Then STRESSCHARACTERVARYINGARR retrieved

  Scenario: GET STRESSINTERVAL12HOURTOMINUTE Endpoint
    Given GET STRESSINTERVAL12HOURTOMINUTE endpoint
    When GET STRESSINTERVAL12HOURTOMINUTE API
    Then STRESSINTERVAL12HOURTOMINUTE retrieved

  Scenario: GET STRESSTIMESTAMPWITHTIMEZONEARR Endpoint
    Given GET STRESSTIMESTAMPWITHTIMEZONEARR endpoint
    When GET STRESSTIMESTAMPWITHTIMEZONEARR API
    Then STRESSTIMESTAMPWITHTIMEZONEARR retrieved

  Scenario: GET STRESSTIMEWITHTIMEZONEARR Endpoint
    Given GET STRESSTIMEWITHTIMEZONEARR endpoint
    When GET STRESSTIMEWITHTIMEZONEARR API
    Then STRESSTIMEWITHTIMEZONEARR retrieved

  Scenario: GET STRESSXML Endpoint
    Given GET STRESSXML endpoint
    When GET STRESSXML API
    Then STRESSXML retrieved

  Scenario: GET STRESSREALARR Endpoint
    Given GET STRESSREALARR endpoint
    When GET STRESSREALARR API
    Then STRESSREALARR retrieved

  Scenario: GET STRESSBIGINTARR Endpoint
    Given GET STRESSBIGINTARR endpoint
    When GET STRESSBIGINTARR API
    Then STRESSBIGINTARR retrieved

  Scenario: GET STRESSBIGSERIAL Endpoint
    Given GET STRESSBIGSERIAL endpoint
    When GET STRESSBIGSERIAL API
    Then STRESSBIGSERIAL retrieved

  Scenario: GET STRESSBITVARYINGARR Endpoint
    Given GET STRESSBITVARYINGARR endpoint
    When GET STRESSBITVARYINGARR API
    Then STRESSBITVARYINGARR retrieved

  Scenario: GET STRESSFLOAT Endpoint
    Given GET STRESSFLOAT endpoint
    When GET STRESSFLOAT API
    Then STRESSFLOAT retrieved

  Scenario: GET STRESSArray Endpoint
    Given GET STRESSArray endpoint
    When GET STRESSArray API
    Then STRESSArray retrieved

  Scenario: GET STRESSINTERVAL09DAYTOHOUR Endpoint
    Given GET STRESSINTERVAL09DAYTOHOUR endpoint
    When GET STRESSINTERVAL09DAYTOHOUR API
    Then STRESSINTERVAL09DAYTOHOUR retrieved

  Scenario: GET STRESSDOUBLEPRECISION Endpoint
    Given GET STRESSDOUBLEPRECISION endpoint
    When GET STRESSDOUBLEPRECISION API
    Then STRESSDOUBLEPRECISION retrieved

  Scenario: GET STRESSUUID Endpoint
    Given GET STRESSUUID endpoint
    When GET STRESSUUID API
    Then STRESSUUID retrieved

  Scenario: GET STRESSDOUBLEPRECISIONARR Endpoint
    Given GET STRESSDOUBLEPRECISIONARR endpoint
    When GET STRESSDOUBLEPRECISIONARR API
    Then STRESSDOUBLEPRECISIONARR retrieved

  Scenario: GET STRESSENUMARR Endpoint
    Given GET STRESSENUMARR endpoint
    When GET STRESSENUMARR API
    Then STRESSENUMARR retrieved

  Scenario: GET STRESSTIMESTAMPWITHTIMEZONE Endpoint
    Given GET STRESSTIMESTAMPWITHTIMEZONE endpoint
    When GET STRESSTIMESTAMPWITHTIMEZONE API
    Then STRESSTIMESTAMPWITHTIMEZONE retrieved

  Scenario: GET STRESSINTERVAL02YEAR Endpoint
    Given GET STRESSINTERVAL02YEAR endpoint
    When GET STRESSINTERVAL02YEAR API
    Then STRESSINTERVAL02YEAR retrieved

  Scenario: GET STRESSSMALLSERIAL Endpoint
    Given GET STRESSSMALLSERIAL endpoint
    When GET STRESSSMALLSERIAL API
    Then STRESSSMALLSERIAL retrieved

  Scenario: GET STRESSINTERVAL14MINUTETOSECOND Endpoint
    Given GET STRESSINTERVAL14MINUTETOSECOND endpoint
    When GET STRESSINTERVAL14MINUTETOSECOND API
    Then STRESSINTERVAL14MINUTETOSECOND retrieved

  Scenario: GET STRESSINTERVAL05HOUR Endpoint
    Given GET STRESSINTERVAL05HOUR endpoint
    When GET STRESSINTERVAL05HOUR API
    Then STRESSINTERVAL05HOUR retrieved

  Scenario: GET STRESSTEXT Endpoint
    Given GET STRESSTEXT endpoint
    When GET STRESSTEXT API
    Then STRESSTEXT retrieved

  Scenario: GET STRESSCHARARR Endpoint
    Given GET STRESSCHARARR endpoint
    When GET STRESSCHARARR API
    Then STRESSCHARARR retrieved

  Scenario: GET STRESSCHAR Endpoint
    Given GET STRESSCHAR endpoint
    When GET STRESSCHAR API
    Then STRESSCHAR retrieved

  Scenario: GET STRESSINTERVAL04DAY Endpoint
    Given GET STRESSINTERVAL04DAY endpoint
    When GET STRESSINTERVAL04DAY API
    Then STRESSINTERVAL04DAY retrieved

  Scenario: GET STRESSINTERVAL13HOURTOSECOND Endpoint
    Given GET STRESSINTERVAL13HOURTOSECOND endpoint
    When GET STRESSINTERVAL13HOURTOSECOND API
    Then STRESSINTERVAL13HOURTOSECOND retrieved

  Scenario: GET STRESSDATEARR Endpoint
    Given GET STRESSDATEARR endpoint
    When GET STRESSDATEARR API
    Then STRESSDATEARR retrieved

  Scenario: GET STRESSINTERVAL10DAYTOMINUTE Endpoint
    Given GET STRESSINTERVAL10DAYTOMINUTE endpoint
    When GET STRESSINTERVAL10DAYTOMINUTE API
    Then STRESSINTERVAL10DAYTOMINUTE retrieved

  Scenario: GET STRESSTIME Endpoint
    Given GET STRESSTIME endpoint
    When GET STRESSTIME API
    Then STRESSTIME retrieved

  Scenario: GET STRESSStaff Endpoint
    Given GET STRESSStaff endpoint
    When GET STRESSStaff API
    Then STRESSStaff retrieved

  Scenario: GET STRESSBIGINT Endpoint
    Given GET STRESSBIGINT endpoint
    When GET STRESSBIGINT API
    Then STRESSBIGINT retrieved

  Scenario: GET STRESSDATE Endpoint
    Given GET STRESSDATE endpoint
    When GET STRESSDATE API
    Then STRESSDATE retrieved

  Scenario: GET STRESSINTERVAL11DAYTOSECOND Endpoint
    Given GET STRESSINTERVAL11DAYTOSECOND endpoint
    When GET STRESSINTERVAL11DAYTOSECOND API
    Then STRESSINTERVAL11DAYTOSECOND retrieved

  Scenario: GET STRESSJSONB Endpoint
    Given GET STRESSJSONB endpoint
    When GET STRESSJSONB API
    Then STRESSJSONB retrieved

  Scenario: GET STRESSNUMERIC Endpoint
    Given GET STRESSNUMERIC endpoint
    When GET STRESSNUMERIC API
    Then STRESSNUMERIC retrieved

  Scenario: GET STRESSUUIDARR Endpoint
    Given GET STRESSUUIDARR endpoint
    When GET STRESSUUIDARR API
    Then STRESSUUIDARR retrieved

  Scenario: GET STRESSJSON Endpoint
    Given GET STRESSJSON endpoint
    When GET STRESSJSON API
    Then STRESSJSON retrieved

  Scenario: GET STRESSINTERVAL07SECOND Endpoint
    Given GET STRESSINTERVAL07SECOND endpoint
    When GET STRESSINTERVAL07SECOND API
    Then STRESSINTERVAL07SECOND retrieved

  Scenario: GET STRESSVirtualParent Endpoint
    Given GET STRESSVirtualParent endpoint
    When GET STRESSVirtualParent API
    Then STRESSVirtualParent retrieved

  Scenario: GET STRESSINTERVAL06MINUTE Endpoint
    Given GET STRESSINTERVAL06MINUTE endpoint
    When GET STRESSINTERVAL06MINUTE API
    Then STRESSINTERVAL06MINUTE retrieved

  Scenario: GET STRESSBITVARYING Endpoint
    Given GET STRESSBITVARYING endpoint
    When GET STRESSBITVARYING API
    Then STRESSBITVARYING retrieved

  Scenario: GET STRESSBIT Endpoint
    Given GET STRESSBIT endpoint
    When GET STRESSBIT API
    Then STRESSBIT retrieved

  Scenario: GET STRESSFLOATARR Endpoint
    Given GET STRESSFLOATARR endpoint
    When GET STRESSFLOATARR API
    Then STRESSFLOATARR retrieved

  Scenario: GET STRESSMONEY Endpoint
    Given GET STRESSMONEY endpoint
    When GET STRESSMONEY API
    Then STRESSMONEY retrieved

  Scenario: GET STRESSSERIAL Endpoint
    Given GET STRESSSERIAL endpoint
    When GET STRESSSERIAL API
    Then STRESSSERIAL retrieved

  Scenario: GET STRESSENUM Endpoint
    Given GET STRESSENUM endpoint
    When GET STRESSENUM API
    Then STRESSENUM retrieved

  Scenario: GET STRESSSMALLINT Endpoint
    Given GET STRESSSMALLINT endpoint
    When GET STRESSSMALLINT API
    Then STRESSSMALLINT retrieved

  Scenario: GET STRESSVirtualParentComplex Endpoint
    Given GET STRESSVirtualParentComplex endpoint
    When GET STRESSVirtualParentComplex API
    Then STRESSVirtualParentComplex retrieved

  Scenario: GET STRESSGEOMPOINT Endpoint
    Given GET STRESSGEOMPOINT endpoint
    When GET STRESSGEOMPOINT API
    Then STRESSGEOMPOINT retrieved

  Scenario: GET STRESSMAXCOLUMN Endpoint
    Given GET STRESSMAXCOLUMN endpoint
    When GET STRESSMAXCOLUMN API
    Then STRESSMAXCOLUMN retrieved

  Scenario: GET STRESSINTERVAL01 Endpoint
    Given GET STRESSINTERVAL01 endpoint
    When GET STRESSINTERVAL01 API
    Then STRESSINTERVAL01 retrieved

  Scenario: GET STRESSSMALLINTARR Endpoint
    Given GET STRESSSMALLINTARR endpoint
    When GET STRESSSMALLINTARR API
    Then STRESSSMALLINTARR retrieved

  Scenario: GET STRESSINTERVAL08YEARTOMONTH Endpoint
    Given GET STRESSINTERVAL08YEARTOMONTH endpoint
    When GET STRESSINTERVAL08YEARTOMONTH API
    Then STRESSINTERVAL08YEARTOMONTH retrieved

  Scenario: GET STRESSBYTEA Endpoint
    Given GET STRESSBYTEA endpoint
    When GET STRESSBYTEA API
    Then STRESSBYTEA retrieved

  Scenario: GET STRESSINTERVAL03MONTH Endpoint
    Given GET STRESSINTERVAL03MONTH endpoint
    When GET STRESSINTERVAL03MONTH API
    Then STRESSINTERVAL03MONTH retrieved

