# Run WebGenAI locally from docker container

# Before running, update ./system/genai/webg_local/webg_config/web_genai.txt
# See: https://apilogicserver.github.io/Docs/WebGenAI-CLI/#configuration

# cd <manager>  

# docker compose -f system/genai/webg_local/docker-compose-webg.yml up
# docker compose -f system/genai/webg_local/docker-compose-webg.yml down

# if you have run docker compose up (above), you must run docker compose down to run directly:

# docker run -it --rm --name webgenai -p 8282:80  --env-file ./system/genai/webg_local/webg_config/web_genai.txt -v ./system/genai/webg_local/webg_temp:/tmp  -v ./system/genai/webg_local/webg_config:/config -v ./system/genai/webg_local/webg_projects:/opt/projects -v /var/run/docker.sock:/var/run/docker.sock --user root apilogicserver/web_genai


name: webgenie
services:
    web_genai:
        stdin_open: true
        tty: true
        container_name: webgenie
        ports:
            - 8282:80
        env_file:
            - ./webg_config/web_genai.txt
        volumes:
            - ./webg_temp:/tmp
            - ./webg_config:/config
            - ./webg_projects:/opt/projects
            - /var/run/docker.sock:/var/run/docker.sock
        image: apilogicserver/web_genai 
        user: root