# Run WebGenAI locally from docker container

# Before running, update ./system/genai/webg_local/webg_config/web_genai.txt
# See: https://apilogicserver.github.io/Docs/WebGenAI-CLI/#configuration

# cd <manager>  

# docker compose -f system/genai/webg_local/docker-compose-webg.yml up
# docker compose -f system/genai/webg_local/docker-compose-webg.yml down

# if you have run docker compose up (above), you must run docker compose down to run directly:
# docker run -it --rm --name webgenie -p 8282:80  --env-file ./system/genai/webg_local/webg_config/web_genai.txt -v ./system/genai/webg_local/webg_temp:/tmp  -v ./system/genai/webg_local/webg_projects:/opt/projects apilogicserver/web_genai

name: webgenie
services:
    web_genai:
        stdin_open: true
        tty: true
        container_name: webgenai
        ports:
            - 8282:80
        env_file:
            - ./../webg_local/webg_config/web_genai.txt
        volumes:
            - ./../webg_local/webg_temp:/tmp
            - ./../webg_local/webg_projects:/opt/projects
            - ./../webg_local/webg_config:/config
        image: apilogicserver/web_genai
#       command: ["python", "/app/other_script.py"]