CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE `users` (`id` char(36) not null, `email` varchar(255) not null, `username` varchar(255) not null, `image` varchar(255) default '', `bio` text default '', `password` varchar(255) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `users_id_unique` on `users` (`id`);
CREATE UNIQUE INDEX `users_email_unique` on `users` (`email`);
CREATE UNIQUE INDEX `users_username_unique` on `users` (`username`);
CREATE TABLE `articles` (`id` char(36) not null, `slug` varchar(255) not null, `title` varchar(255) not null, `body` text not null, `description` varchar(255) not null, `favorites_count` integer not null default '0', `author` char(36) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, foreign key(`author`) references `users`(`id`) on delete CASCADE, primary key (`id`));
CREATE UNIQUE INDEX `articles_id_unique` on `articles` (`id`);
CREATE UNIQUE INDEX `articles_slug_unique` on `articles` (`slug`);
CREATE TABLE `comments` (`id` char(36) not null, `body` text not null, `author` char(36) not null, `article` char(36) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, foreign key(`author`) references `users`(`id`) on delete CASCADE, foreign key(`article`) references `articles`(`id`) on delete CASCADE, primary key (`id`));
CREATE UNIQUE INDEX `comments_id_unique` on `comments` (`id`);
CREATE TABLE `favorites` (`id` char(36) not null, `user` char(36) not null, `article` char(36) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, foreign key(`user`) references `users`(`id`) on delete CASCADE, foreign key(`article`) references `articles`(`id`) on delete CASCADE, primary key (`id`));
CREATE UNIQUE INDEX `favorites_id_unique` on `favorites` (`id`);
CREATE TABLE `followers` (`id` char(36) not null, `user` char(36) not null, `follower` char(36) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, foreign key(`user`) references `users`(`id`) on delete CASCADE, foreign key(`follower`) references `users`(`id`) on delete CASCADE, primary key (`id`));
CREATE UNIQUE INDEX `followers_id_unique` on `followers` (`id`);
CREATE UNIQUE INDEX `followers_user_follower_unique` on `followers` (`user`, `follower`);
CREATE TABLE `tags` (`id` char(36) not null, `name` varchar(255) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `tags_id_unique` on `tags` (`id`);
CREATE UNIQUE INDEX `tags_name_unique` on `tags` (`name`);
CREATE TABLE `articles_tags` (`id` char(36) not null, `article` char(36) not null, `tag` char(36) not null, `created_at` datetime not null default CURRENT_TIMESTAMP, `updated_at` datetime not null default CURRENT_TIMESTAMP, foreign key(`article`) references `articles`(`id`) on delete CASCADE, foreign key(`tag`) references `tags`(`id`) on delete CASCADE, primary key (`id`));
CREATE UNIQUE INDEX `articles_tags_id_unique` on `articles_tags` (`id`);
CREATE UNIQUE INDEX `articles_tags_tag_article_unique` on `articles_tags` (`tag`, `article`);