--------------------------------------------------------
--  Constraints for Table ARI_023_NOTES
--------------------------------------------------------

  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("NOTESID" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("SHIPID" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("NOTES" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("CREATE_TMSTP" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("UPDATE_TMSTP" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("CREATE_UID" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" MODIFY ("UPDATE_UID" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_NOTES" ADD CONSTRAINT "ARI_023_NOTES_PK" PRIMARY KEY ("NOTESID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSAMTEST_TS"  ENABLE;
