--------------------------------------------------------
--  Constraints for Table ARI_023_SHIPMENTS
--------------------------------------------------------

  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("ARRIVALDATE" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("FLT" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("AWBNUM" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("PC" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("CREATE_TMSTP" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("UPDATE_TMSTP" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("CREATE_UID" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("UPDATE_UID" NOT NULL ENABLE);
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" ADD CHECK ("ARRIVALDATE" = trunc("ARRIVALDATE")) ENABLE;
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" ADD CHECK ("REC" is null or "REC" = 'Yes') ENABLE;
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" ADD CONSTRAINT "PK_ARI_023_SHIPMENTS" PRIMARY KEY ("SHIPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSAMTEST_TS"  ENABLE;
  ALTER TABLE "CSAMTEST_SCHEMA"."ARI_023_SHIPMENTS" MODIFY ("SHIPID" NOT NULL ENABLE);
