SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MVXJDTA].[OOLINE](
	[OBCONO] [numeric](3, 0) NOT NULL,
	[OBDIVI] [nchar](3) NOT NULL,
	[OBORNO] [nchar](10) NOT NULL,
	[OBPONR] [numeric](5, 0) NOT NULL,
	[OBPOSX] [numeric](3, 0) NOT NULL,
	[OBLTYP] [nchar](1) NOT NULL,
	[OBORST] [nchar](2) NOT NULL,
	[OBFACI] [nchar](3) NOT NULL,
	[OBWHLO] [nchar](3) NOT NULL,
	[OBITNO] [nchar](15) NOT NULL,
	[OBREPI] [nchar](15) NOT NULL,
	[OBITDS] [nvarchar](30) NOT NULL,
	[OBTEDS] [nvarchar](60) NOT NULL,
	[OBORQT] [numeric](15, 6) NOT NULL,
	[OBORQA] [numeric](15, 6) NOT NULL,
	[OBRNQT] [numeric](15, 6) NOT NULL,
	[OBRNQA] [numeric](15, 6) NOT NULL,
	[OBALQT] [numeric](15, 6) NOT NULL,
	[OBALQA] [numeric](15, 6) NOT NULL,
	[OBPLQT] [numeric](15, 6) NOT NULL,
	[OBPLQA] [numeric](15, 6) NOT NULL,
	[OBDLQT] [numeric](15, 6) NOT NULL,
	[OBDLQA] [numeric](15, 6) NOT NULL,
	[OBIVQT] [numeric](15, 6) NOT NULL,
	[OBIVQA] [numeric](15, 6) NOT NULL,
	[OBDCCD] [numeric](1, 0) NOT NULL,
	[OBALUN] [nchar](3) NOT NULL,
	[OBDCCA] [numeric](1, 0) NOT NULL,
	[OBCOFA] [numeric](15, 9) NOT NULL,
	[OBDMCF] [numeric](1, 0) NOT NULL,
	[OBSPUN] [nchar](3) NOT NULL,
	[OBPCOF] [numeric](15, 9) NOT NULL,
	[OBDCCS] [numeric](1, 0) NOT NULL,
	[OBCOFS] [numeric](15, 9) NOT NULL,
	[OBDMCS] [numeric](1, 0) NOT NULL,
	[OBPOPN] [nvarchar](30) NOT NULL,
	[OBALWT] [numeric](2, 0) NOT NULL,
	[OBALWQ] [nchar](4) NOT NULL,
	[OBSAPR] [numeric](17, 6) NOT NULL,
	[OBNEPR] [numeric](17, 6) NOT NULL,
	[OBSACD] [numeric](5, 0) NOT NULL,
	[OBPRMO] [nchar](1) NOT NULL,
	[OBDIC1] [numeric](1, 0) NOT NULL,
	[OBDIC2] [numeric](1, 0) NOT NULL,
	[OBDIC3] [numeric](1, 0) NOT NULL,
	[OBDIC4] [numeric](1, 0) NOT NULL,
	[OBDIC5] [numeric](1, 0) NOT NULL,
	[OBDIC6] [numeric](1, 0) NOT NULL,
	[OBDIP1] [numeric](5, 2) NOT NULL,
	[OBDIP2] [numeric](5, 2) NOT NULL,
	[OBDIP3] [numeric](5, 2) NOT NULL,
	[OBDIP4] [numeric](5, 2) NOT NULL,
	[OBDIP5] [numeric](5, 2) NOT NULL,
	[OBDIP6] [numeric](5, 2) NOT NULL,
	[OBDIA1] [numeric](15, 2) NOT NULL,
	[OBDIA2] [numeric](15, 2) NOT NULL,
	[OBDIA3] [numeric](15, 2) NOT NULL,
	[OBDIA4] [numeric](15, 2) NOT NULL,
	[OBDIA5] [numeric](15, 2) NOT NULL,
	[OBDIA6] [numeric](15, 2) NOT NULL,
	[OBCMP1] [nchar](4) NOT NULL,
	[OBCMP2] [nchar](4) NOT NULL,
	[OBCMP3] [nchar](4) NOT NULL,
	[OBCMP4] [nchar](4) NOT NULL,
	[OBCMP5] [nchar](4) NOT NULL,
	[OBCMP6] [nchar](4) NOT NULL,
	[OBDIBE] [nchar](1) NOT NULL,
	[OBDIRE] [nchar](1) NOT NULL,
	[OBDCHA] [numeric](1, 0) NOT NULL,
	[OBDPST] [numeric](1, 0) NOT NULL,
	[OBDDSU] [numeric](1, 0) NOT NULL,
	[OBIDSC] [numeric](1, 0) NOT NULL,
	[OBACRF] [nchar](8) NOT NULL,
	[OBOTDI] [numeric](1, 0) NOT NULL,
	[OBDWDT] [numeric](8, 0) NOT NULL,
	[OBDWHM] [numeric](4, 0) NOT NULL,
	[OBCODT] [numeric](8, 0) NOT NULL,
	[OBCOHM] [numeric](4, 0) NOT NULL,
	[OBDWDZ] [numeric](8, 0) NOT NULL,
	[OBDWHZ] [numeric](4, 0) NOT NULL,
	[OBCODZ] [numeric](8, 0) NOT NULL,
	[OBCOHZ] [numeric](4, 0) NOT NULL,
	[OBTIZO] [nchar](5) NOT NULL,
	[OBDLTS] [numeric](4, 0) NOT NULL,
	[OBSTCD] [numeric](1, 0) NOT NULL,
	[OBPRCH] [numeric](1, 0) NOT NULL,
	[OBRORC] [numeric](1, 0) NOT NULL,
	[OBRORN] [nchar](10) NOT NULL,
	[OBRORL] [numeric](6, 0) NOT NULL,
	[OBUCOS] [numeric](17, 6) NOT NULL,
	[OBCOCD] [numeric](5, 0) NOT NULL,
	[OBUCCD] [numeric](1, 0) NOT NULL,
	[OBCMNO] [nchar](4) NOT NULL,
	[OBHDPR] [nchar](15) NOT NULL,
	[OBCFIN] [numeric](10, 0) NOT NULL,
	[OBECVS] [numeric](3, 0) NOT NULL,
	[OBVTCD] [numeric](2, 0) NOT NULL,
	[OBJDCD] [nchar](5) NOT NULL,
	[OBDLSP] [nchar](12) NOT NULL,
	[OBLNAM] [numeric](15, 2) NOT NULL,
	[OBLNA2] [numeric](15, 2) NOT NULL,
	[OBDINR] [numeric](5, 0) NOT NULL,
	[OBDISX] [numeric](3, 0) NOT NULL,
	[OBAGNO] [nchar](7) NOT NULL,
	[OBBAGC] [nchar](10) NOT NULL,
	[OBBAGD] [numeric](8, 0) NOT NULL,
	[OBAGLN] [numeric](7, 0) NOT NULL,
	[OBPRRF] [nchar](2) NOT NULL,
	[OBNTCD] [numeric](1, 0) NOT NULL,
	[OBCNQT] [numeric](15, 6) NOT NULL,
	[OBEDFP] [numeric](17, 6) NOT NULL,
	[OBSMCD] [nchar](10) NOT NULL,
	[OBBNCD] [numeric](1, 0) NOT NULL,
	[OBPRAC] [numeric](1, 0) NOT NULL,
	[OBVRCD] [nchar](2) NOT NULL,
	[OBECLC] [nchar](2) NOT NULL,
	[OBORCO] [nchar](3) NOT NULL,
	[OBPRTX] [numeric](13, 0) NOT NULL,
	[OBPOTX] [numeric](13, 0) NOT NULL,
	[OBDTID] [numeric](13, 0) NOT NULL,
	[OBDELS] [numeric](1, 0) NOT NULL,
	[OBE0PA] [nvarchar](17) NOT NULL,
	[OBDSGP] [nchar](2) NOT NULL,
	[OBMOYE] [nchar](15) NOT NULL,
	[OBPUSN] [nvarchar](17) NOT NULL,
	[OBPUTP] [numeric](1, 0) NOT NULL,
	[OBQTQL] [numeric](1, 0) NOT NULL,
	[OBTEPA] [nchar](3) NOT NULL,
	[OBPACT] [nchar](6) NOT NULL,
	[OBCUPA] [nvarchar](20) NOT NULL,
	[OBD1QT] [numeric](15, 6) NOT NULL,
	[OBCUNO] [nchar](10) NOT NULL,
	[OBCUOR] [nvarchar](20) NOT NULL,
	[OBCUPO] [numeric](7, 0) NOT NULL,
	[OBCUSX] [numeric](3, 0) NOT NULL,
	[OBSMCC] [numeric](1, 0) NOT NULL,
	[OBRSCD] [nchar](3) NOT NULL,
	[OBMUFT] [numeric](2, 0) NOT NULL,
	[OBINPR] [numeric](17, 6) NOT NULL,
	[OBCUCT] [nchar](3) NOT NULL,
	[OBABNO] [numeric](1, 0) NOT NULL,
	[OBPROJ] [nchar](7) NOT NULL,
	[OBELNO] [nchar](8) NOT NULL,
	[OBBPAT] [nchar](6) NOT NULL,
	[OBBPST] [numeric](1, 0) NOT NULL,
	[OBNOAA] [numeric](1, 0) NOT NULL,
	[OBCPRE] [nchar](5) NOT NULL,
	[OBHAFE] [nchar](6) NOT NULL,
	[OBCAWE] [numeric](15, 6) NOT NULL,
	[OBWHSL] [nchar](10) NOT NULL,
	[OBBANO] [nvarchar](20) NOT NULL,
	[OBCAMU] [nvarchar](20) NOT NULL,
	[OBADID] [nchar](6) NOT NULL,
	[OBROUT] [nchar](6) NOT NULL,
	[OBRODN] [numeric](3, 0) NOT NULL,
	[OBDSDT] [numeric](8, 0) NOT NULL,
	[OBDSHM] [numeric](4, 0) NOT NULL,
	[OBDSTX] [nvarchar](36) NOT NULL,
	[OBDEFC] [numeric](3, 0) NOT NULL,
	[OBPLDT] [numeric](8, 0) NOT NULL,
	[OBPLHM] [numeric](4, 0) NOT NULL,
	[OBSRCD] [numeric](1, 0) NOT NULL,
	[OBSPLC] [nchar](2) NOT NULL,
	[OBDLBU] [numeric](1, 0) NOT NULL,
	[OBSPOS] [numeric](3, 0) NOT NULL,
	[OBFDED] [numeric](8, 0) NOT NULL,
	[OBLDED] [numeric](8, 0) NOT NULL,
	[OBAETY] [numeric](1, 0) NOT NULL,
	[OBATNR] [numeric](17, 0) NOT NULL,
	[OBSCMO] [nchar](6) NOT NULL,
	[OBPRPR] [numeric](1, 0) NOT NULL,
	[OBCINA] [numeric](1, 0) NOT NULL,
	[OBATV1] [numeric](15, 6) NOT NULL,
	[OBATV2] [numeric](15, 6) NOT NULL,
	[OBATV3] [numeric](15, 6) NOT NULL,
	[OBATV4] [numeric](15, 6) NOT NULL,
	[OBATV5] [numeric](15, 6) NOT NULL,
	[OBATV6] [nchar](15) NOT NULL,
	[OBATV7] [nchar](15) NOT NULL,
	[OBATV8] [nchar](15) NOT NULL,
	[OBATV9] [nchar](15) NOT NULL,
	[OBATV0] [nchar](15) NOT NULL,
	[OBCNNR] [numeric](11, 0) NOT NULL,
	[OBMNIN] [nchar](1) NOT NULL,
	[OBREPN] [numeric](10, 0) NOT NULL,
	[OBATPR] [nchar](1) NOT NULL,
	[OBATMO] [nchar](10) NOT NULL,
	[OBORTY] [nchar](3) NOT NULL,
	[OBSUNO] [nchar](10) NOT NULL,
	[OBPUPR] [numeric](17, 6) NOT NULL,
	[OBPUCD] [numeric](5, 0) NOT NULL,
	[OBPPUN] [nchar](3) NOT NULL,
	[OBCUCD] [nchar](3) NOT NULL,
	[OBODI1] [numeric](5, 2) NOT NULL,
	[OBODI2] [numeric](5, 2) NOT NULL,
	[OBODI3] [numeric](5, 2) NOT NULL,
	[OBOURR] [nchar](10) NOT NULL,
	[OBOURT] [nchar](1) NOT NULL,
	[OBBUYE] [nchar](10) NOT NULL,
	[OBFWHL] [nchar](3) NOT NULL,
	[OBPRNO] [nchar](15) NOT NULL,
	[OBSCHN] [numeric](11, 0) NOT NULL,
	[OBMODL] [nchar](3) NOT NULL,
	[OBTEDL] [nchar](3) NOT NULL,
	[OBTEL2] [nvarchar](36) NOT NULL,
	[OBRGDT] [numeric](8, 0) NOT NULL,
	[OBRGTM] [numeric](6, 0) NOT NULL,
	[OBLMDT] [numeric](8, 0) NOT NULL,
	[OBCHNO] [numeric](3, 0) NOT NULL,
	[OBCHID] [nchar](10) NOT NULL,
	[OBRORX] [numeric](3, 0) NOT NULL,
	[OBLMTS] [numeric](18, 0) NOT NULL,
	[OBRTQA] [numeric](15, 6) NOT NULL,
	[OBRTQT] [numeric](15, 6) NOT NULL,
	[OBPRHL] [nchar](15) NOT NULL,
	[OBSERN] [nvarchar](20) NOT NULL,
	[OBCTNO] [nchar](10) NOT NULL,
	[OBAPBA] [numeric](1, 0) NOT NULL,
	[OBCFGL] [nchar](15) NOT NULL,
	[OBWATP] [nchar](10) NOT NULL,
	[OBGWTP] [nchar](10) NOT NULL,
	[OBPRHW] [nchar](15) NOT NULL,
	[OBSERW] [nvarchar](20) NOT NULL,
	[OBPWNR] [numeric](5, 0) NOT NULL,
	[OBPWSX] [numeric](3, 0) NOT NULL,
	[OBEWST] [numeric](1, 0) NOT NULL,
	[OBAGNB] [nchar](7) NOT NULL,
	[OBCTNS] [nchar](10) NOT NULL,
	[OBWATQ] [numeric](1, 0) NOT NULL,
	[OBTECN] [nvarchar](20) NOT NULL,
	[OBINAP] [nchar](15) NOT NULL,
	[OBPCNR] [numeric](5, 0) NOT NULL,
	[OBPCSU] [numeric](3, 0) NOT NULL,
	[OBRELI] [numeric](5, 0) NOT NULL,
	[OBPIDE] [nchar](4) NOT NULL,
	[OBPCLA] [numeric](17, 6) NOT NULL,
	[OBBOP1] [numeric](1, 0) NOT NULL,
	[OBSCLB] [numeric](15, 2) NOT NULL,
	[OBOFNO] [nchar](10) NOT NULL,
	[OBVERS] [numeric](2, 0) NOT NULL,
	[OBOFNR] [numeric](5, 0) NOT NULL,
	[OBOFSX] [numeric](3, 0) NOT NULL,
	[OBDECU] [nchar](10) NOT NULL,
	[OBTEPY] [nchar](3) NOT NULL,
	[OBARST] [numeric](2, 0) NOT NULL,
	[OBRSC1] [nchar](3) NOT NULL,
	[OBPMOR] [numeric](1, 0) NOT NULL,
	[OBCBSM] [numeric](1, 0) NOT NULL,
	[OBINIP] [numeric](1, 0) NOT NULL,
	[OBUPAV] [numeric](1, 0) NOT NULL,
	[OBQTBC] [numeric](15, 6) NOT NULL,
	[OBMPID] [numeric](1, 0) NOT NULL,
	[OBTOMU] [numeric](15, 6) NOT NULL,
	[OBENNO] [nchar](10) NOT NULL,
	[OBLNCL] [numeric](1, 0) NOT NULL,
	[OBPRIO] [numeric](1, 0) NOT NULL,
	[OBCCSA] [numeric](17, 6) NOT NULL,
	[OBRAGN] [nchar](15) NOT NULL,
	[OBRASN] [nchar](10) NOT NULL,
	[OBCLAT] [nchar](2) NOT NULL
) ON [TMVXSD]
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE CLUSTERED INDEX [OOLINE00] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSD]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20180904-162917] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBDWDT] ASC
)
INCLUDE([OBORNO],[OBPONR],[OBORST],[OBWHLO],[OBITNO],[OBORQT],[OBSAPR],[OBUCOS]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSD]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE11] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBHDPR] ASC,
	[OBWHLO] ASC,
	[OBALUN] ASC,
	[OBORST] ASC,
	[OBCODT] ASC,
	[OBCOHM] ASC,
	[OBADID] ASC,
	[OBLTYP] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE21] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBWHLO] ASC,
	[OBITNO] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC,
	[OBALQT] ASC,
	[OBPLQT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE30] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBJDCD] ASC,
	[OBCODT] ASC,
	[OBCOHM] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE31] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBJDCD] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE40] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBRORC] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE41] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBDIVI] ASC,
	[OBDWDT] ASC
)
INCLUDE([OBORNO],[OBPONR],[OBORST],[OBWHLO],[OBITNO],[OBORQT],[OBSAPR],[OBUCOS]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSD]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE50] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBORST] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE54] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBORST] DESC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE60] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBADID] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE70] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBAGNO] ASC,
	[OBCUNO] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE71] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBCUNO] ASC,
	[OBITNO] ASC,
	[OBCODZ] ASC,
	[OBADID] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE75] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBAGNO] ASC,
	[OBBAGC] ASC,
	[OBBAGD] ASC,
	[OBAGLN] ASC,
	[OBDWDT] ASC,
	[OBDWHM] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE80] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBITNO] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE85] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBPWNR] ASC,
	[OBPWSX] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE90] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBPROJ] ASC,
	[OBELNO] ASC,
	[OBITNO] ASC,
	[OBWHLO] ASC,
	[OBCUNO] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE94] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBITNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE95] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBOFNO] ASC,
	[OBVERS] ASC,
	[OBOFNR] ASC,
	[OBOFSX] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE96] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBORNO] ASC,
	[OBWHLO] ASC,
	[OBITNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [OOLINE97] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBREPN] ASC,
	[OBRELI] ASC,
	[OBORNO] ASC,
	[OBPONR] ASC,
	[OBPOSX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSI]
GO
CREATE NONCLUSTERED INDEX [OOLINE98] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBSAPR] ASC
)
INCLUDE([OBORNO],[OBPONR],[OBORST],[OBITNO],[OBORQT],[OBDWDT],[OBCUOR]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSD]
GO
CREATE NONCLUSTERED INDEX [OOLINE99] ON [MVXJDTA].[OOLINE]
(
	[OBCONO] ASC,
	[OBSAPR] ASC
)
INCLUDE([OBORNO],[OBPONR],[OBORST],[OBITNO],[OBORQT],[OBDWDT],[OBUCOS],[OBCUOR],[OBDIVI]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXSD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCONO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDIVI]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBORNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPONR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPOSX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBLTYP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBORST]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBFACI]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBWHLO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBITNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBREPI]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBITDS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTEDS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBORQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBORQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRNQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRNQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBALQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBALQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPLQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPLQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDLQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDLQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBIVQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBIVQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDCCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBALUN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDCCA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCOFA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDMCF]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSPUN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPCOF]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDCCS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCOFS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDMCS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPOPN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBALWT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBALWQ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSAPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBNEPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSACD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPRMO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIC1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIC2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIC3]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIC4]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIC5]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIC6]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIP1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIP2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIP3]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIP4]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIP5]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIP6]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIA1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIA2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIA3]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIA4]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIA5]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDIA6]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMP1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMP2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMP3]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMP4]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMP5]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMP6]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDIBE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDIRE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDCHA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDPST]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDDSU]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBIDSC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBACRF]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBOTDI]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDWDT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDWHM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCODT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCOHM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDWDZ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDWHZ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCODZ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCOHZ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTIZO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDLTS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSTCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPRCH]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRORC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBRORN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRORL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBUCOS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCOCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBUCCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCMNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBHDPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCFIN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBECVS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBVTCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBJDCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDLSP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBLNAM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBLNA2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDINR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDISX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBAGNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBBAGC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBBAGD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBAGLN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPRRF]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBNTCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCNQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBEDFP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSMCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBBNCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPRAC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBVRCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBECLC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBORCO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPRTX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPOTX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDTID]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDELS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBE0PA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDSGP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBMOYE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPUSN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPUTP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBQTQL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTEPA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPACT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCUPA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBD1QT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCUNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCUOR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCUPO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCUSX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSMCC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBRSCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBMUFT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBINPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCUCT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBABNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPROJ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBELNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBBPAT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBBPST]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBNOAA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCPRE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBHAFE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCAWE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBWHSL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBBANO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCAMU]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBADID]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBROUT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRODN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDSDT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDSHM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDSTX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDEFC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPLDT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPLHM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSRCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSPLC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBDLBU]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSPOS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBFDED]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBLDED]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBAETY]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBATNR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSCMO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPRPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCINA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBATV1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBATV2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBATV3]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBATV4]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBATV5]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATV6]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATV7]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATV8]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATV9]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATV0]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCNNR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBMNIN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBREPN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBATMO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBORTY]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSUNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPUPR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPUCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPPUN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCUCD]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBODI1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBODI2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBODI3]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBOURR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBOURT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBBUYE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBFWHL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPRNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSCHN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBMODL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTEDL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTEL2]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRGDT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRGTM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBLMDT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCHNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCHID]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRORX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBLMTS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRTQA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRTQT]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPRHL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSERN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCTNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBAPBA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCFGL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBWATP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBGWTP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPRHW]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBSERW]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPWNR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPWSX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBEWST]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBAGNB]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCTNS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBWATQ]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTECN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBINAP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPCNR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPCSU]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBRELI]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBPIDE]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPCLA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBBOP1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBSCLB]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBOFNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBVERS]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBOFNR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBOFSX]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBDECU]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBTEPY]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBARST]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBRSC1]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPMOR]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCBSM]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBINIP]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBUPAV]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBQTBC]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBMPID]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBTOMU]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBENNO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBLNCL]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBPRIO]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ((0)) FOR [OBCCSA]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBRAGN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBRASN]
GO
ALTER TABLE [MVXJDTA].[OOLINE] ADD  DEFAULT ('') FOR [OBCLAT]
GO
