// Copy this text, paste to https://dbdiagram.io/d

Table Category {
    Id None
    CategoryName_ColumnName None
    Description None
    Client_id None
    }

Table Customer {
    Id None
    CompanyName None
    ContactName None
    ContactTitle None
    Address None
    City None
    Region None
    PostalCode None
    Country None
    Phone None
    Fax None
    Balance DECIMAL
    CreditLimit DECIMAL
    OrderCount None
    UnpaidOrderCount None
    Client_id None
    }

Table CustomerDemographic {
    Id None
    CustomerDesc None
    }

Table Department {
    Id None
    DepartmentId None
    DepartmentName None
    SecurityLevel None
    }

Table Employee {
    Id None
    LastName None
    FirstName None
    Title None
    TitleOfCourtesy None
    BirthDate None
    HireDate None
    Address None
    City None
    Region None
    PostalCode None
    Country None
    HomePhone None
    Extension None
    Notes None
    ReportsTo None
    PhotoPath None
    EmployeeType None
    Salary DECIMAL
    WorksForDepartmentId None
    OnLoanDepartmentId None
    UnionId None
    Dues DECIMAL
    }

Table Union {
    Id None
    Name None
    }

Table EmployeeAudit {
    Id None
    Title None
    Salary DECIMAL
    LastName None
    FirstName None
    EmployeeId None
    CreatedOn None
    UpdatedOn None
    CreatedBy None
    UpdatedBy None
    }

Table EmployeeTerritory {
    Id None
    EmployeeId None
    TerritoryId None
    }

Table Territory {
    Id None
    TerritoryDescription None
    RegionId None
    }

Table Location {
    country None
    city None
    notes None
    }

Table Order {
    Id None
    CustomerId None
    EmployeeId None
    OrderDate None
    RequiredDate DATE
    ShippedDate None
    ShipVia None
    Freight DECIMAL
    ShipName None
    ShipAddress None
    ShipCity None
    ShipRegion None
    ShipPostalCode None
    ShipCountry None
    AmountTotal None
    Country None
    City None
    Ready None
    OrderDetailCount None
    CloneFromOrder None
    }

Table OrderDetail {
    Id None
    OrderId None
    ProductId None
    UnitPrice DECIMAL
    Quantity None
    Discount None
    Amount DECIMAL
    ShippedDate None
    }

Table Product {
    Id None
    ProductName None
    SupplierId None
    CategoryId None
    QuantityPerUnit None
    UnitPrice DECIMAL
    UnitsInStock None
    UnitsOnOrder None
    ReorderLevel None
    Discontinued None
    UnitsShipped None
    }

Table Region {
    Id None
    RegionDescription None
    }

Table SampleDBVersion {
    Id None
    Notes None
    }

Table Shipper {
    Id None
    CompanyName None
    Phone None
    }

Table Supplier {
    Id None
    CompanyName None
    ContactName None
    ContactTitle None
    Address None
    City None
    Region None
    PostalCode None
    Country None
    Phone None
    Fax None
    HomePage None
    }



// Relationships
    Ref: Department.(DepartmentId) < Department.(Id)
    Ref: Employee.(OnLoanDepartmentId) < Department.(Id)
    Ref: Employee.(UnionId) < Union.(Id)
    Ref: Employee.(WorksForDepartmentId) < Department.(Id)
    Ref: EmployeeAudit.(EmployeeId) < Employee.(Id)
    Ref: EmployeeTerritory.(EmployeeId) < Employee.(Id)
    Ref: EmployeeTerritory.(TerritoryId) < Territory.(Id)
    Ref: Order.(CloneFromOrder) < Order.(Id)
    Ref: Order.(City, Country) < Location.(country, country)
    Ref: Order.(CustomerId) < Customer.(Id)
    Ref: Order.(EmployeeId) < Employee.(Id)
    Ref: OrderDetail.(OrderId) < Order.(Id)
    Ref: OrderDetail.(ProductId) < Product.(Id)
