SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dates](
	[dt] [date] NOT NULL,
	[d]  AS (datepart(day,[dt])),
	[y]  AS (datepart(year,[dt])),
	[q]  AS (datepart(quarter,[dt])),
	[m]  AS (datepart(month,[dt])),
	[fm]  AS (dateadd(month,datediff(month,(0),[dt]),(0))),
	[w]  AS (datepart(week,[dt])),
	[wd]  AS (datepart(weekday,[dt])),
	[mn]  AS (datename(month,[dt])),
	[s101]  AS (CONVERT([char](10),[dt],(101))),
	[s103]  AS (CONVERT([char](10),[dt],(103))),
	[s112]  AS (CONVERT([char](8),[dt],(112))),
PRIMARY KEY CLUSTERED
(
	[dt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [TMVXTEMP]
) ON [TMVXTEMP]
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
CREATE NONCLUSTERED INDEX [i1] ON [dbo].[Dates]
(
	[s112] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [TMVXTEMP]
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
CREATE NONCLUSTERED INDEX [s112_index] ON [dbo].[Dates]
(
	[s112] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [TMVXTEMP]
GO
