"""Add sys_supplier_req table

Revision ID: 947ef4eae2dc
Revises: 
Create Date: 2026-02-05 17:07:39.532104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947ef4eae2dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_supplier_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.String(length=2000), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('chosen_supplier_id', sa.Integer(), nullable=True),
    sa.Column('chosen_unit_price', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_supplier_req_item_id'), 'sys_supplier_req', ['item_id'], unique=False)
    op.create_index(op.f('ix_sys_supplier_req_product_id'), 'sys_supplier_req', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_supplier_req_product_id'), table_name='sys_supplier_req')
    op.drop_index(op.f('ix_sys_supplier_req_item_id'), table_name='sys_supplier_req')
    op.drop_table('sys_supplier_req')
    # ### end Alembic commands ###
